apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecotrace-postgres-pvc
  namespace: ecotrace
  labels:
    app.kubernetes.io/name: ecotrace-postgres
    app.kubernetes.io/part-of: ecotrace-engine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
