apiVersion: v1
kind: Secret
metadata:
  name: ecotrace-secrets
  namespace: ecotrace
  labels:
    app.kubernetes.io/part-of: ecotrace-engine
type: Opaque
stringData:
  POSTGRES_USER: "ecotrace"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  RABBITMQ_USER: "ecotrace"
  RABBITMQ_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
